import static org.junit.Assert.*;
import java.util.ArrayList;
import org.junit.Test;

public class TestPebbleBag {

	pebbleBag testBag = new pebbleBag("testingBag");
	
	@Test
	public void testfillNewPebbles() {
		ArrayList<Integer> intList = new ArrayList<Integer>(); //Create a empty list of integers
		for(int i = 0; i < 3; i++) { //Add 0,1,2 to the integer list
			intList.add(i);
		}
		ArrayList<pebble> pebbleList = new ArrayList<pebble>(); //Create an empty list of pebbles
		for(int j = 0; j < 3; j++) { //Add pebbles with weights 0,1,2 to the integer list
			pebbleList.add(new pebble(j));
		}
		int checkIndex = 0; //Beginning from 0
		for(pebble currentNewPebble : testBag.fillNewPebbles(intList)) { //For every pebble generated by fillNewPebbles
			assertEquals(currentNewPebble.getWeight(),pebbleList.get(checkIndex).getWeight()); //Check that it is equal
			checkIndex++;
		}
	}
	
	@Test
	public void testisEmpty() {
		testBag.emptyBag(); //Empty the bag
		assertTrue(testBag.isEmpty()); //Check if the bag is empty
	}
}
